# Generated by Django 5.2.16 on 2026-07-22 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='配方代碼')),
                ('name', models.CharField(max_length=200, verbose_name='配方名稱')),
                ('output_qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='標準產出量')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('output_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_recipes', to='inventory.product', verbose_name='產出原料')),
            ],
            options={
                'verbose_name': '配方',
                'verbose_name_plural': '配方',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='工單號')),
                ('planned_qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='計劃產量')),
                ('actual_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='實際產量')),
                ('status', models.CharField(choices=[('planned', '已排程'), ('in_progress', '生產中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='狀態')),
                ('planned_start', models.DateField(verbose_name='計劃開始日')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='計劃完成日')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='實際開始')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='實際完成')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='產出批次號')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立人')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.recipe', verbose_name='配方')),
            ],
            options={
                'verbose_name': '生產工單',
                'verbose_name_plural': '生產工單',
                'ordering': ['-planned_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='用量')),
                ('loss_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='損耗率(%)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.product', verbose_name='投入原料')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.recipe', verbose_name='配方')),
            ],
            options={
                'verbose_name': '配方明細',
                'verbose_name_plural': '配方明細',
            },
        ),
    ]
