# Generated by Django 5.2.16 on 2026-07-21 11:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='客戶代碼')),
                ('name', models.CharField(max_length=200, verbose_name='客戶名稱')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='銷售單號')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已確認'), ('picking', '揀貨中'), ('shipped', '已出貨'), ('delivered', '已送達'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('order_date', models.DateField(verbose_name='訂單日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交貨日期')),
                ('shipping_address', models.CharField(blank=True, max_length=300, verbose_name='送貨地址')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '銷售訂單',
                'verbose_name_plural': '銷售訂單',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='單價')),
                ('shipped_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='已出貨數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_items', to='inventory.product', verbose_name='原料')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='銷售訂單')),
            ],
            options={
                'verbose_name': '銷售明細',
                'verbose_name_plural': '銷售明細',
            },
        ),
    ]
