# Generated by Django 5.2.16 on 2026-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='信用額度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_day',
            field=models.CharField(blank=True, max_length=100, verbose_name='固定配送日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_sequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='配送順序'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='發票地址'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='最後交易日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='customer',
            name='map_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='地圖'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_3',
            field=models.CharField(blank=True, max_length=30, verbose_name='電話 3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='區域'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='配送地址'),
        ),
    ]
