from django.db import migrations, models


def seed_revision(apps, schema_editor):
    CustomerSearchRevision = apps.get_model("sales", "CustomerSearchRevision")
    CustomerSearchRevision.objects.get_or_create(pk=1, defaults={"version": 0})


def create_revision_table_if_missing(apps, schema_editor):
    """Skip CREATE when table already exists (e.g. prior 0006 deploy via railway up)."""
    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)
    if "sales_customersearchrevision" in tables:
        return
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE TABLE sales_customersearchrevision (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                version bigint NOT NULL CHECK (version >= 0)
            )
            """
        )
    else:
        schema_editor.execute(
            """
            CREATE TABLE sales_customersearchrevision (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                version integer unsigned NOT NULL CHECK (version >= 0)
            )
            """
        )


def remove_orphan_0006_migration_record(apps, schema_editor):
    """Drop stale 0006 row if an earlier deploy applied the renamed migration."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DELETE FROM django_migrations
            WHERE app = %s AND name = %s
            """,
            ["sales", "0006_customer_search_revision"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_customer_voice_aliases"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="CustomerSearchRevision",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("version", models.PositiveBigIntegerField(default=0, verbose_name="版本")),
                    ],
                    options={
                        "verbose_name": "客戶搜尋版本",
                        "verbose_name_plural": "客戶搜尋版本",
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_revision_table_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.RunPython(seed_revision, migrations.RunPython.noop),
        migrations.RunPython(remove_orphan_0006_migration_record, migrations.RunPython.noop),
    ]
