# Generated by Django 5.2.16 on 2026-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_customerproductprice_unique_open_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='special_price_reason',
            field=models.CharField(blank=True, choices=[('pre_increase', '漲價前優惠'), ('bulk_purchase', '大量採購優惠'), ('long_term_customer', '長期客戶優惠'), ('special_favor', '特殊優待'), ('compensation', '補償客戶'), ('price_commitment', '報價承諾'), ('other', '其他')], default='', max_length=30, verbose_name='特殊成交原因'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='special_price_reason_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='特殊成交原因說明'),
        ),
    ]
