# Generated by Django 5.2.16 on 2026-07-22 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='供應商代碼')),
                ('name', models.CharField(max_length=200, verbose_name='供應商名稱')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('certification', models.CharField(blank=True, max_length=200, verbose_name='認證(如 HACCP/ISO)')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='採購單號')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待審核'), ('approved', '已核准'), ('ordered', '已下單'), ('partial', '部分到貨'), ('received', '已到貨'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('order_date', models.DateField(verbose_name='下單日期')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='預計到貨日')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '採購單',
                'verbose_name_plural': '採購單',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=30, unique=True, verbose_name='入庫單號')),
                ('received_date', models.DateField(verbose_name='到貨日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='驗收人')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseorder', verbose_name='採購單')),
            ],
            options={
                'verbose_name': '採購入庫',
                'verbose_name_plural': '採購入庫',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='採購數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='單價')),
                ('received_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='已到貨數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.product', verbose_name='原料')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder', verbose_name='採購單')),
            ],
            options={
                'verbose_name': '採購明細',
                'verbose_name_plural': '採購明細',
            },
        ),
    ]
