# Generated by Django 5.2.16 on 2026-07-22 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='料號')),
                ('name', models.CharField(max_length=200, verbose_name='品名')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分類')),
                ('unit', models.CharField(choices=[('kg', '公斤'), ('g', '公克'), ('l', '公升'), ('ml', '毫升'), ('pcs', '件'), ('box', '箱')], default='kg', max_length=10, verbose_name='單位')),
                ('shelf_life_days', models.PositiveIntegerField(default=365, verbose_name='標準保質期(天)')),
                ('storage_temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最低儲存溫度(°C)')),
                ('storage_temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最高儲存溫度(°C)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='倉庫代碼')),
                ('name', models.CharField(max_length=100, verbose_name='倉庫名稱')),
                ('temperature_zone', models.CharField(choices=[('ambient', '常溫'), ('chilled', '冷藏 (0-4°C)'), ('frozen', '冷凍 (-18°C)'), ('controlled', '恆溫控濕')], default='ambient', max_length=20, verbose_name='溫區')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '倉庫',
                'verbose_name_plural': '倉庫',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次號')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='數量')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生產日期')),
                ('expiry_date', models.DateField(verbose_name='有效期限')),
                ('status', models.CharField(choices=[('available', '可用'), ('quarantine', '待檢'), ('expired', '已過期'), ('depleted', '已耗盡')], default='available', max_length=20, verbose_name='狀態')),
                ('supplier_batch', models.CharField(blank=True, max_length=50, verbose_name='供應商批號')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product', verbose_name='原料')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '庫存批次',
                'verbose_name_plural': '庫存批次',
                'ordering': ['expiry_date'],
                'unique_together': {('product', 'batch_no', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in_purchase', '採購入庫'), ('in_production', '生產入庫'), ('in_adjust', '盤盈調整'), ('out_sales', '銷售出庫'), ('out_production', '生產領料'), ('out_adjust', '盤虧調整'), ('transfer', '調撥')], max_length=20, verbose_name='類型')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='數量')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='參考單號')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch', verbose_name='批次')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '庫存異動',
                'verbose_name_plural': '庫存異動',
                'ordering': ['-created_at'],
            },
        ),
    ]
