# Generated by Django 5.2.16 on 2026-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku'], 'verbose_name': '產品', 'verbose_name_plural': '產品'},
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_raw_material',
            field=models.BooleanField(default=False, verbose_name='可做原料'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='是否販售'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('finished', '成品'), ('raw', '原料'), ('dual', '成品/原料')], default='raw', max_length=20, verbose_name='產品類型'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.CharField(blank=True, max_length=200, verbose_name='規格'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='每公斤成本'),
        ),
    ]
