# Generated by Django 5.2.16 on 2026-07-30 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_order_void_and_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField(verbose_name='出車日期')),
                ('trip_number', models.PositiveIntegerField(verbose_name='趟次')),
                ('trip_code', models.CharField(max_length=30, unique=True, verbose_name='出車代碼')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('departed', '已出車'), ('completed', '已完成'), ('cancelled', '已取消')], default='preparing', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='出車時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
            ],
            options={
                'verbose_name': '出車趟次',
                'verbose_name_plural': '出車趟次',
                'ordering': ['-trip_date', '-trip_number'],
                'constraints': [models.UniqueConstraint(fields=('trip_date', 'trip_number'), name='deliveries_trip_date_number_uniq')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTripOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='配送順序')),
                ('status', models.CharField(choices=[('pending', '待配送'), ('delivered', '已送達'), ('failed', '未送達')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('delivery_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_orders', to='deliveries.deliverytrip', verbose_name='出車趟次')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_trip_order', to='sales.salesorder', verbose_name='銷售訂單')),
            ],
            options={
                'verbose_name': '出車訂單',
                'verbose_name_plural': '出車訂單',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('delivery_trip', 'sequence'), name='deliveries_trip_sequence_uniq')],
            },
        ),
    ]
