# Generated by Django 5.2.16 on 2026-07-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetAiConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AI控制台',
                'verbose_name_plural': 'AI控制台',
                'db_table': 'AI控制台',
            },
        ),
        migrations.CreateModel(
            name='SheetHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_today_delivery', models.CharField(blank=True, db_column='🚚 今日配送', max_length=100, verbose_name='🚚 今日配送')),
                ('stat_today_payment', models.CharField(blank=True, db_column='💰 今日收款', max_length=100, verbose_name='💰 今日收款')),
                ('stat_today_purchase', models.CharField(blank=True, db_column='📦 今日採購', max_length=100, verbose_name='📦 今日採購')),
                ('stat_today_reminder', models.CharField(blank=True, db_column='⚠ 今日提醒', max_length=100, verbose_name='⚠ 今日提醒')),
                ('ai_suggestion_1', models.CharField(blank=True, db_column='今天沒有待收款', max_length=300, verbose_name='今天沒有待收款')),
                ('ai_suggestion_2', models.CharField(blank=True, db_column='今天共有5家配送', max_length=300, verbose_name='今天共有5家配送')),
                ('ai_suggestion_3', models.CharField(blank=True, db_column='建議先配送仁武區', max_length=300, verbose_name='建議先配送仁武區')),
            ],
            options={
                'verbose_name': '首頁',
                'verbose_name_plural': '首頁',
                'db_table': '首頁',
            },
        ),
        migrations.CreateModel(
            name='SheetImprovementCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '改善中心',
                'verbose_name_plural': '改善中心',
                'db_table': '改善中心',
            },
        ),
        migrations.CreateModel(
            name='SheetInventoryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '庫存管理',
                'verbose_name_plural': '庫存管理',
                'db_table': '庫存管理',
            },
        ),
        migrations.CreateModel(
            name='SheetPaymentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '收款管理',
                'verbose_name_plural': '收款管理',
                'db_table': '收款管理',
            },
        ),
        migrations.CreateModel(
            name='SheetPriceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '價格管理',
                'verbose_name_plural': '價格管理',
                'db_table': '價格管理',
            },
        ),
        migrations.CreateModel(
            name='SheetProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '生產記錄',
                'verbose_name_plural': '生產記錄',
                'db_table': '生產記錄',
            },
        ),
        migrations.CreateModel(
            name='SheetSupplierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '供應商資料',
                'verbose_name_plural': '供應商資料',
                'db_table': '供應商資料',
            },
        ),
        migrations.CreateModel(
            name='SheetSystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
                'db_table': '系統設定',
            },
        ),
        migrations.CreateModel(
            name='SheetVendorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '廠商資料',
                'verbose_name_plural': '廠商資料',
                'db_table': '廠商資料',
            },
        ),
        migrations.CreateModel(
            name='SheetCustomerData',
            fields=[
                ('customer_code', models.CharField(db_column='客戶編號', max_length=20, primary_key=True, serialize=False, verbose_name='客戶編號')),
                ('region', models.CharField(blank=True, db_column='區域', max_length=100, verbose_name='區域')),
                ('customer_name', models.CharField(db_column='客戶名稱', max_length=200, unique=True, verbose_name='客戶名稱')),
                ('contact_person', models.CharField(blank=True, db_column='聯絡人', max_length=100, verbose_name='聯絡人')),
                ('phone_1', models.CharField(blank=True, db_column='📞_1', max_length=50, verbose_name='📞')),
                ('phone_2', models.CharField(blank=True, db_column='📞_2', max_length=50, verbose_name='📞')),
                ('phone_3', models.CharField(blank=True, db_column='📞_3', max_length=50, verbose_name='📞')),
                ('delivery_address', models.CharField(blank=True, db_column='配送地址', max_length=300, verbose_name='配送地址')),
                ('invoice_address', models.CharField(blank=True, db_column='發票地址', max_length=300, verbose_name='發票地址')),
                ('map_link', models.CharField(blank=True, db_column='📍', max_length=100, verbose_name='📍')),
                ('line_id', models.CharField(blank=True, db_column='🟩Line', max_length=100, verbose_name='🟩Line')),
                ('payment_method', models.CharField(blank=True, db_column='付款方式', max_length=100, verbose_name='付款方式')),
                ('fixed_delivery_day', models.CharField(blank=True, db_column='固定配送日', max_length=100, verbose_name='固定配送日')),
                ('delivery_sequence', models.IntegerField(blank=True, db_column='配送順序', null=True, verbose_name='配送順序')),
                ('credit_limit', models.DecimalField(blank=True, db_column='信用額度', decimal_places=2, max_digits=14, null=True, verbose_name='信用額度')),
                ('last_transaction_date', models.DateField(blank=True, db_column='最後交易日', null=True, verbose_name='最後交易日')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
            ],
            options={
                'verbose_name': '客戶資料',
                'verbose_name_plural': '客戶資料',
                'db_table': '客戶資料',
                'indexes': [models.Index(fields=['customer_name'], name='idx_customer_name'), models.Index(fields=['region'], name='idx_customer_region'), models.Index(fields=['phone_1'], name='idx_customer_phone_1'), models.Index(fields=['phone_2'], name='idx_customer_phone_2'), models.Index(fields=['phone_3'], name='idx_customer_phone_3')],
            },
        ),
        migrations.CreateModel(
            name='SheetOrderCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_input', models.CharField(blank=True, db_column='🔍 輸入電話或客戶名稱…', max_length=200, verbose_name='🔍 輸入電話或客戶名稱…')),
                ('customer_name', models.CharField(blank=True, db_column='客戶姓名', max_length=200, verbose_name='客戶姓名')),
                ('phone_1', models.CharField(blank=True, db_column='電話_1', max_length=50, verbose_name='電話')),
                ('address_1', models.CharField(blank=True, db_column='地址_1', max_length=300, verbose_name='地址')),
                ('payment_method_1', models.CharField(blank=True, db_column='付款方式_1', max_length=100, verbose_name='付款方式')),
                ('region', models.CharField(blank=True, db_column='區域', max_length=100, verbose_name='區域')),
                ('order_date', models.DateField(blank=True, db_column='訂單日期', null=True, verbose_name='訂單日期')),
                ('order_customer', models.CharField(blank=True, db_column='客戶', max_length=200, verbose_name='客戶')),
                ('phone_2', models.CharField(blank=True, db_column='電話_2', max_length=50, verbose_name='電話')),
                ('address_2', models.CharField(blank=True, db_column='地址_2', max_length=300, verbose_name='地址')),
                ('payment_method_2', models.CharField(blank=True, db_column='付款方式_2', max_length=100, verbose_name='付款方式')),
                ('product_name', models.CharField(blank=True, db_column='品名', max_length=200, verbose_name='品名')),
                ('quantity', models.DecimalField(blank=True, db_column='數量', decimal_places=3, max_digits=14, null=True, verbose_name='數量')),
                ('unit', models.CharField(blank=True, db_column='單位', max_length=50, verbose_name='單位')),
            ],
            options={
                'verbose_name': '接單中心',
                'verbose_name_plural': '接單中心',
                'db_table': '接單中心',
                'indexes': [models.Index(fields=['search_input'], name='idx_order_center_search'), models.Index(fields=['customer_name'], name='idx_order_center_custname'), models.Index(fields=['phone_1'], name='idx_order_center_phone1'), models.Index(fields=['order_date'], name='idx_order_center_orderdate')],
            },
        ),
        migrations.CreateModel(
            name='SheetProductData',
            fields=[
                ('product_code', models.CharField(db_column='產品編號', max_length=20, primary_key=True, serialize=False, verbose_name='產品編號')),
                ('product_name', models.CharField(db_column='產品名稱', max_length=200, unique=True, verbose_name='產品名稱')),
                ('product_type', models.CharField(blank=True, db_column='產品類型', max_length=100, verbose_name='產品類型')),
                ('specification', models.CharField(blank=True, db_column='規格', max_length=200, verbose_name='規格')),
                ('unit', models.CharField(blank=True, db_column='單位', max_length=50, verbose_name='單位')),
                ('is_for_sale', models.CharField(blank=True, db_column='是否販售', max_length=10, verbose_name='是否販售')),
                ('can_be_raw_material', models.CharField(blank=True, db_column='可做原料', max_length=10, verbose_name='可做原料')),
                ('is_active', models.CharField(blank=True, db_column='啟用', max_length=10, verbose_name='啟用')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('cost', models.DecimalField(blank=True, db_column='成本', decimal_places=2, max_digits=14, null=True, verbose_name='成本')),
                ('price', models.DecimalField(blank=True, db_column='售價', decimal_places=2, max_digits=14, null=True, verbose_name='售價')),
            ],
            options={
                'verbose_name': '產品資料',
                'verbose_name_plural': '產品資料',
                'db_table': '產品資料',
                'indexes': [models.Index(fields=['product_name'], name='idx_product_name'), models.Index(fields=['product_type'], name='idx_product_type'), models.Index(fields=['is_active'], name='idx_product_active')],
            },
        ),
        migrations.CreateModel(
            name='SheetRawMaterialData',
            fields=[
                ('material_code', models.CharField(db_column='原料編號', max_length=20, primary_key=True, serialize=False, verbose_name='原料編號')),
                ('material_name', models.CharField(db_column='原料名稱', max_length=200, verbose_name='原料名稱')),
                ('category', models.CharField(blank=True, db_column='分類', max_length=100, verbose_name='分類')),
                ('unit', models.CharField(blank=True, db_column='單位', max_length=50, verbose_name='單位')),
                ('cost_per_kg', models.DecimalField(blank=True, db_column='每公斤成本', decimal_places=4, max_digits=14, null=True, verbose_name='每公斤成本')),
                ('latest_purchase_price', models.DecimalField(blank=True, db_column='最新採購價', decimal_places=4, max_digits=14, null=True, verbose_name='最新採購價')),
                ('last_purchase_date', models.DateField(blank=True, db_column='最近採購日', null=True, verbose_name='最近採購日')),
                ('safety_stock', models.DecimalField(blank=True, db_column='安全庫存', decimal_places=3, max_digits=14, null=True, verbose_name='安全庫存')),
                ('is_active', models.CharField(blank=True, db_column='啟用', max_length=10, verbose_name='啟用')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
            ],
            options={
                'verbose_name': '原料資料',
                'verbose_name_plural': '原料資料',
                'db_table': '原料資料',
                'indexes': [models.Index(fields=['material_name'], name='idx_material_name'), models.Index(fields=['category'], name='idx_material_category')],
            },
        ),
        migrations.CreateModel(
            name='SheetRecipeMaster',
            fields=[
                ('recipe_id', models.CharField(db_column='配方ID', max_length=20, primary_key=True, serialize=False, verbose_name='配方ID')),
                ('product_name', models.CharField(blank=True, db_column='產品名稱', max_length=200, verbose_name='產品名稱')),
                ('product_type', models.CharField(blank=True, db_column='產品類型', max_length=100, verbose_name='產品類型')),
                ('product_feature', models.CharField(blank=True, db_column='產品特性', max_length=200, verbose_name='產品特性')),
                ('recipe_version', models.CharField(blank=True, db_column='配方版本', max_length=50, verbose_name='配方版本')),
                ('base_batch_kg', models.DecimalField(blank=True, db_column='基準批次(kg)', decimal_places=3, max_digits=14, null=True, verbose_name='基準批次(kg)')),
                ('status', models.CharField(blank=True, db_column='狀態', max_length=50, verbose_name='狀態')),
                ('created_date', models.DateField(blank=True, db_column='建立日期', null=True, verbose_name='建立日期')),
                ('change_reason', models.CharField(blank=True, db_column='修改原因', max_length=300, verbose_name='修改原因')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('total_cost', models.DecimalField(blank=True, db_column='總成本', decimal_places=4, max_digits=14, null=True, verbose_name='總成本')),
                ('cost_per_kg', models.DecimalField(blank=True, db_column='每公斤成本', decimal_places=4, max_digits=14, null=True, verbose_name='每公斤成本')),
                ('product', models.ForeignKey(db_column='產品編號', on_delete=django.db.models.deletion.PROTECT, related_name='recipe_masters', to='excel_schema.sheetproductdata', verbose_name='產品編號')),
            ],
            options={
                'verbose_name': '配方主檔',
                'verbose_name_plural': '配方主檔',
                'db_table': '配方主檔',
            },
        ),
        migrations.CreateModel(
            name='SheetRecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(db_column='項次', verbose_name='項次')),
                ('material_name', models.CharField(blank=True, db_column='原料名稱', max_length=200, verbose_name='原料名稱')),
                ('selected_item', models.CharField(blank=True, db_column='採用品項', max_length=200, verbose_name='採用品項')),
                ('quantity', models.DecimalField(blank=True, db_column='用量', decimal_places=3, max_digits=14, null=True, verbose_name='用量')),
                ('unit', models.CharField(blank=True, db_column='單位', max_length=50, verbose_name='單位')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('cost_per_kg', models.DecimalField(blank=True, db_column='每公斤成本', decimal_places=4, max_digits=14, null=True, verbose_name='每公斤成本')),
                ('cost', models.DecimalField(blank=True, db_column='成本', decimal_places=4, max_digits=14, null=True, verbose_name='成本')),
                ('material', models.ForeignKey(db_column='原料編號', on_delete=django.db.models.deletion.PROTECT, related_name='recipe_details', to='excel_schema.sheetrawmaterialdata', verbose_name='原料編號')),
                ('recipe', models.ForeignKey(db_column='配方ID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='excel_schema.sheetrecipemaster', verbose_name='配方ID')),
            ],
            options={
                'verbose_name': '配方明細',
                'verbose_name_plural': '配方明細',
                'db_table': '配方明細',
            },
        ),
        migrations.CreateModel(
            name='SheetTodayDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, db_column='配送日期', null=True, verbose_name='配送日期')),
                ('delivery_area', models.CharField(blank=True, db_column='配送區', max_length=100, verbose_name='配送區')),
                ('address', models.CharField(blank=True, db_column='地址', max_length=300, verbose_name='地址')),
                ('quantity', models.DecimalField(blank=True, db_column='數量', decimal_places=3, max_digits=14, null=True, verbose_name='數量')),
                ('delivery_sequence', models.IntegerField(blank=True, db_column='配送順序', null=True, verbose_name='配送順序')),
                ('status', models.CharField(blank=True, db_column='狀態', max_length=50, verbose_name='狀態')),
                ('completed_at', models.DateTimeField(blank=True, db_column='完成時間', null=True, verbose_name='完成時間')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('customer', models.ForeignKey(blank=True, db_column='客戶', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='today_deliveries', to='excel_schema.sheetcustomerdata', to_field='customer_name', verbose_name='客戶')),
                ('product', models.ForeignKey(blank=True, db_column='產品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='today_deliveries', to='excel_schema.sheetproductdata', to_field='product_name', verbose_name='產品')),
            ],
            options={
                'verbose_name': '今日配送',
                'verbose_name_plural': '今日配送',
                'db_table': '今日配送',
            },
        ),
        migrations.CreateModel(
            name='SheetDeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, db_column='客戶名稱', max_length=200, verbose_name='客戶名稱')),
                ('weekday', models.CharField(blank=True, db_column='星期', max_length=20, verbose_name='星期')),
                ('delivery_area', models.CharField(blank=True, db_column='配送區', max_length=100, verbose_name='配送區')),
                ('delivery_sequence', models.IntegerField(blank=True, db_column='配送順序', null=True, verbose_name='配送順序')),
                ('fixed_quantity', models.DecimalField(blank=True, db_column='固定數量', decimal_places=3, max_digits=14, null=True, verbose_name='固定數量')),
                ('is_delivery', models.CharField(blank=True, db_column='是否配送', max_length=10, verbose_name='是否配送')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('created_date', models.DateField(blank=True, db_column='建立日期', null=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(blank=True, db_column='最後更新', null=True, verbose_name='最後更新')),
                ('customer', models.ForeignKey(db_column='客戶編號', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='excel_schema.sheetcustomerdata', verbose_name='客戶編號')),
                ('fixed_product', models.ForeignKey(blank=True, db_column='固定產品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_rules', to='excel_schema.sheetproductdata', verbose_name='固定產品')),
            ],
            options={
                'verbose_name': '配送規則',
                'verbose_name_plural': '配送規則',
                'db_table': '配送規則',
                'indexes': [models.Index(fields=['weekday'], name='idx_delivery_rule_weekday'), models.Index(fields=['delivery_area'], name='idx_delivery_rule_area')],
            },
        ),
        migrations.CreateModel(
            name='SheetQuickSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(blank=True, db_column='🔍 搜尋客戶', max_length=200, verbose_name='🔍 搜尋客戶')),
                ('region', models.CharField(blank=True, db_column='區域', max_length=100, verbose_name='區域')),
                ('customer_name', models.CharField(blank=True, db_column='客戶名稱', max_length=200, verbose_name='客戶名稱')),
                ('contact_person', models.CharField(blank=True, db_column='聯絡人', max_length=100, verbose_name='聯絡人')),
                ('phone_1', models.CharField(blank=True, db_column='📞_1', max_length=50, verbose_name='📞')),
                ('phone_2', models.CharField(blank=True, db_column='📞_2', max_length=50, verbose_name='📞')),
                ('phone_3', models.CharField(blank=True, db_column='📞_3', max_length=50, verbose_name='📞')),
                ('map_address', models.CharField(blank=True, db_column='📍地址', max_length=300, verbose_name='📍地址')),
                ('create_order_action', models.CharField(blank=True, db_column='🛒 建立訂單', max_length=100, verbose_name='🛒 建立訂單')),
                ('customer', models.ForeignKey(blank=True, db_column='客戶編號', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_search_rows', to='excel_schema.sheetcustomerdata', verbose_name='客戶編號')),
            ],
            options={
                'verbose_name': '快速查詢',
                'verbose_name_plural': '快速查詢',
                'db_table': '快速查詢',
                'indexes': [models.Index(fields=['search_keyword'], name='idx_quick_search_keyword'), models.Index(fields=['customer_name'], name='idx_quick_search_name'), models.Index(fields=['region'], name='idx_quick_search_region')],
            },
        ),
        migrations.CreateModel(
            name='SheetPurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(db_column='進貨單號', max_length=50, verbose_name='進貨單號')),
                ('receipt_date', models.DateField(blank=True, db_column='日期', null=True, verbose_name='日期')),
                ('material_name', models.CharField(blank=True, db_column='原料名稱', max_length=200, verbose_name='原料名稱')),
                ('quantity', models.DecimalField(blank=True, db_column='數量', decimal_places=3, max_digits=14, null=True, verbose_name='數量')),
                ('unit_price', models.DecimalField(blank=True, db_column='單價', decimal_places=4, max_digits=14, null=True, verbose_name='單價')),
                ('supplier_name', models.CharField(blank=True, db_column='供應商', max_length=200, verbose_name='供應商')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('material', models.ForeignKey(db_column='原料編號', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='excel_schema.sheetrawmaterialdata', verbose_name='原料編號')),
            ],
            options={
                'verbose_name': '採購進貨',
                'verbose_name_plural': '採購進貨',
                'db_table': '採購進貨',
                'indexes': [models.Index(fields=['receipt_date'], name='idx_purchase_receipt_date'), models.Index(fields=['supplier_name'], name='idx_purchase_supplier')],
                'constraints': [models.UniqueConstraint(fields=('receipt_no', 'material'), name='uniq_purchase_receipt_line')],
            },
        ),
        migrations.CreateModel(
            name='SheetRecipeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, db_column='產品名稱', max_length=200, verbose_name='產品名稱')),
                ('version', models.CharField(blank=True, db_column='版本', max_length=50, verbose_name='版本')),
                ('material_name', models.CharField(blank=True, db_column='原料名稱', max_length=200, verbose_name='原料名稱')),
                ('quantity', models.DecimalField(blank=True, db_column='用量', decimal_places=3, max_digits=14, null=True, verbose_name='用量')),
                ('unit', models.CharField(blank=True, db_column='單位', max_length=50, verbose_name='單位')),
                ('sort_order', models.IntegerField(blank=True, db_column='排序', null=True, verbose_name='排序')),
                ('is_active', models.CharField(blank=True, db_column='是否啟用', max_length=10, verbose_name='是否啟用')),
                ('notes', models.TextField(blank=True, db_column='備註', verbose_name='備註')),
                ('material', models.ForeignKey(db_column='原料編號', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_management_rows', to='excel_schema.sheetrawmaterialdata', verbose_name='原料編號')),
                ('product', models.ForeignKey(db_column='產品編號', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_management_rows', to='excel_schema.sheetproductdata', verbose_name='產品編號')),
            ],
            options={
                'verbose_name': '配方管理',
                'verbose_name_plural': '配方管理',
                'db_table': '配方管理',
                'indexes': [models.Index(fields=['version'], name='idx_recipe_mgmt_version'), models.Index(fields=['sort_order'], name='idx_recipe_mgmt_sort')],
            },
        ),
        migrations.AddIndex(
            model_name='sheetrecipemaster',
            index=models.Index(fields=['product_name'], name='idx_recipe_master_pname'),
        ),
        migrations.AddIndex(
            model_name='sheetrecipemaster',
            index=models.Index(fields=['status'], name='idx_recipe_master_status'),
        ),
        migrations.AddIndex(
            model_name='sheetrecipedetail',
            index=models.Index(fields=['item_no'], name='idx_recipe_detail_itemno'),
        ),
        migrations.AddConstraint(
            model_name='sheetrecipedetail',
            constraint=models.UniqueConstraint(fields=('recipe', 'item_no'), name='uniq_recipe_detail_item'),
        ),
        migrations.AddIndex(
            model_name='sheettodaydelivery',
            index=models.Index(fields=['delivery_date'], name='idx_today_delivery_date'),
        ),
        migrations.AddIndex(
            model_name='sheettodaydelivery',
            index=models.Index(fields=['delivery_area'], name='idx_today_delivery_area'),
        ),
        migrations.AddIndex(
            model_name='sheettodaydelivery',
            index=models.Index(fields=['status'], name='idx_today_delivery_status'),
        ),
    ]
