CREATE INDEX "idx_recipe_master_pname" ON "配方主檔" ("產品名稱")
CREATE INDEX "idx_recipe_master_status" ON "配方主檔" ("狀態")
CREATE INDEX "idx_recipe_detail_itemno" ON "配方明細" ("項次")
ALTER TABLE "配方明細" ADD CONSTRAINT "uniq_recipe_detail_item" UNIQUE ("配方ID", "項次")
CREATE INDEX "idx_today_delivery_date" ON "今日配送" ("配送日期")
CREATE INDEX "idx_today_delivery_area" ON "今日配送" ("配送區")
CREATE INDEX "idx_today_delivery_status" ON "今日配送" ("狀態")
CREATE INDEX "客戶資料_客戶編號_31883a00_like" ON "客戶資料" ("客戶編號" varchar_pattern_ops)
CREATE INDEX "客戶資料_客戶名稱_8dcbd63a_like" ON "客戶資料" ("客戶名稱" varchar_pattern_ops)
CREATE INDEX "idx_customer_name" ON "客戶資料" ("客戶名稱")
CREATE INDEX "idx_customer_region" ON "客戶資料" ("區域")
CREATE INDEX "idx_customer_phone_1" ON "客戶資料" ("📞_1")
CREATE INDEX "idx_customer_phone_2" ON "客戶資料" ("📞_2")
CREATE INDEX "idx_customer_phone_3" ON "客戶資料" ("📞_3")
CREATE INDEX "idx_order_center_search" ON "接單中心" ("🔍 輸入電話或客戶名稱…")
CREATE INDEX "idx_order_center_custname" ON "接單中心" ("客戶姓名")
CREATE INDEX "idx_order_center_phone1" ON "接單中心" ("電話_1")
CREATE INDEX "idx_order_center_orderdate" ON "接單中心" ("訂單日期")
CREATE INDEX "產品資料_產品編號_91bba7bc_like" ON "產品資料" ("產品編號" varchar_pattern_ops)
CREATE INDEX "產品資料_產品名稱_341e015f_like" ON "產品資料" ("產品名稱" varchar_pattern_ops)
CREATE INDEX "idx_product_name" ON "產品資料" ("產品名稱")
CREATE INDEX "idx_product_type" ON "產品資料" ("產品類型")
CREATE INDEX "idx_product_active" ON "產品資料" ("啟用")
CREATE INDEX "原料資料_原料編號_b42b085c_like" ON "原料資料" ("原料編號" varchar_pattern_ops)
CREATE INDEX "idx_material_name" ON "原料資料" ("原料名稱")
CREATE INDEX "idx_material_category" ON "原料資料" ("分類")
ALTER TABLE "配方主檔" ADD CONSTRAINT "配方主檔_產品編號_830aff56_fk_產品資料_產品編號" FOREIGN KEY ("產品編號") REFERENCES "產品資料" ("產品編號") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "配方主檔_配方ID_633f97ef_like" ON "配方主檔" ("配方ID" varchar_pattern_ops)
CREATE INDEX "配方主檔_產品編號_830aff56" ON "配方主檔" ("產品編號")
CREATE INDEX "配方主檔_產品編號_830aff56_like" ON "配方主檔" ("產品編號" varchar_pattern_ops)
ALTER TABLE "配方明細" ADD CONSTRAINT "配方明細_原料編號_d151e6ab_fk_原料資料_原料編號" FOREIGN KEY ("原料編號") REFERENCES "原料資料" ("原料編號") DEFERRABLE INITIALLY DEFERRED
ALTER TABLE "配方明細" ADD CONSTRAINT "配方明細_配方ID_84d4a3c8_fk_配方主檔_配方ID" FOREIGN KEY ("配方ID") REFERENCES "配方主檔" ("配方ID") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "配方明細_原料編號_d151e6ab" ON "配方明細" ("原料編號")
CREATE INDEX "配方明細_原料編號_d151e6ab_like" ON "配方明細" ("原料編號" varchar_pattern_ops)
CREATE INDEX "配方明細_配方ID_84d4a3c8" ON "配方明細" ("配方ID")
CREATE INDEX "配方明細_配方ID_84d4a3c8_like" ON "配方明細" ("配方ID" varchar_pattern_ops)
ALTER TABLE "今日配送" ADD CONSTRAINT "今日配送_客戶_87324b88_fk_客戶資料_客戶名稱" FOREIGN KEY ("客戶") REFERENCES "客戶資料" ("客戶名稱") DEFERRABLE INITIALLY DEFERRED
ALTER TABLE "今日配送" ADD CONSTRAINT "今日配送_產品_e08bc199_fk_產品資料_產品名稱" FOREIGN KEY ("產品") REFERENCES "產品資料" ("產品名稱") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "今日配送_客戶_87324b88" ON "今日配送" ("客戶")
CREATE INDEX "今日配送_客戶_87324b88_like" ON "今日配送" ("客戶" varchar_pattern_ops)
CREATE INDEX "今日配送_產品_e08bc199" ON "今日配送" ("產品")
CREATE INDEX "今日配送_產品_e08bc199_like" ON "今日配送" ("產品" varchar_pattern_ops)
ALTER TABLE "配送規則" ADD CONSTRAINT "配送規則_客戶編號_fe1f193c_fk_客戶資料_客戶編號" FOREIGN KEY ("客戶編號") REFERENCES "客戶資料" ("客戶編號") DEFERRABLE INITIALLY DEFERRED
ALTER TABLE "配送規則" ADD CONSTRAINT "配送規則_固定產品_c3d7f13f_fk_產品資料_產品編號" FOREIGN KEY ("固定產品") REFERENCES "產品資料" ("產品編號") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "配送規則_客戶編號_fe1f193c" ON "配送規則" ("客戶編號")
CREATE INDEX "配送規則_客戶編號_fe1f193c_like" ON "配送規則" ("客戶編號" varchar_pattern_ops)
CREATE INDEX "配送規則_固定產品_c3d7f13f" ON "配送規則" ("固定產品")
CREATE INDEX "配送規則_固定產品_c3d7f13f_like" ON "配送規則" ("固定產品" varchar_pattern_ops)
CREATE INDEX "idx_delivery_rule_weekday" ON "配送規則" ("星期")
CREATE INDEX "idx_delivery_rule_area" ON "配送規則" ("配送區")
ALTER TABLE "快速查詢" ADD CONSTRAINT "快速查詢_客戶編號_a3254066_fk_客戶資料_客戶編號" FOREIGN KEY ("客戶編號") REFERENCES "客戶資料" ("客戶編號") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "快速查詢_客戶編號_a3254066" ON "快速查詢" ("客戶編號")
CREATE INDEX "快速查詢_客戶編號_a3254066_like" ON "快速查詢" ("客戶編號" varchar_pattern_ops)
CREATE INDEX "idx_quick_search_keyword" ON "快速查詢" ("🔍 搜尋客戶")
CREATE INDEX "idx_quick_search_name" ON "快速查詢" ("客戶名稱")
CREATE INDEX "idx_quick_search_region" ON "快速查詢" ("區域")
ALTER TABLE "採購進貨" ADD CONSTRAINT "採購進貨_原料編號_9f467f6a_fk_原料資料_原料編號" FOREIGN KEY ("原料編號") REFERENCES "原料資料" ("原料編號") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "採購進貨_原料編號_9f467f6a" ON "採購進貨" ("原料編號")
CREATE INDEX "採購進貨_原料編號_9f467f6a_like" ON "採購進貨" ("原料編號" varchar_pattern_ops)
CREATE INDEX "idx_purchase_receipt_date" ON "採購進貨" ("日期")
CREATE INDEX "idx_purchase_supplier" ON "採購進貨" ("供應商")
ALTER TABLE "配方管理" ADD CONSTRAINT "配方管理_原料編號_41d4d950_fk_原料資料_原料編號" FOREIGN KEY ("原料編號") REFERENCES "原料資料" ("原料編號") DEFERRABLE INITIALLY DEFERRED
ALTER TABLE "配方管理" ADD CONSTRAINT "配方管理_產品編號_21617951_fk_產品資料_產品編號" FOREIGN KEY ("產品編號") REFERENCES "產品資料" ("產品編號") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "配方管理_原料編號_41d4d950" ON "配方管理" ("原料編號")
CREATE INDEX "配方管理_原料編號_41d4d950_like" ON "配方管理" ("原料編號" varchar_pattern_ops)
CREATE INDEX "配方管理_產品編號_21617951" ON "配方管理" ("產品編號")
CREATE INDEX "配方管理_產品編號_21617951_like" ON "配方管理" ("產品編號" varchar_pattern_ops)
CREATE INDEX "idx_recipe_mgmt_version" ON "配方管理" ("版本")
CREATE INDEX "idx_recipe_mgmt_sort" ON "配方管理" ("排序")
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL)
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops)
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date")