CREATE TABLE "sales_customer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(20) NOT NULL UNIQUE, "name" varchar(200) NOT NULL, "contact_person" varchar(100) NOT NULL, "phone" varchar(30) NOT NULL, "email" varchar(254) NOT NULL, "address" varchar(300) NOT NULL, "tax_id" varchar(20) NOT NULL, "is_active" boolean NOT NULL, "notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL)
CREATE TABLE "sales_salesorder" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "order_no" varchar(30) NOT NULL UNIQUE, "status" varchar(20) NOT NULL, "order_date" date NOT NULL, "delivery_date" date NULL, "shipping_address" varchar(300) NOT NULL, "notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "created_by_id" integer NULL, "customer_id" bigint NOT NULL)
CREATE TABLE "sales_salesorderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" numeric(12, 3) NOT NULL, "unit_price" numeric(12, 2) NOT NULL, "shipped_qty" numeric(12, 3) NOT NULL, "product_id" bigint NOT NULL, "sales_order_id" bigint NOT NULL)
CREATE INDEX "sales_customer_code_53eb8090_like" ON "sales_customer" ("code" varchar_pattern_ops)
ALTER TABLE "sales_salesorder" ADD CONSTRAINT "sales_salesorder_created_by_id_0700fb7b_fk_auth_user_id" FOREIGN KEY ("created_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
ALTER TABLE "sales_salesorder" ADD CONSTRAINT "sales_salesorder_customer_id_e8577187_fk_sales_customer_id" FOREIGN KEY ("customer_id") REFERENCES "sales_customer" ("id") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "sales_salesorder_order_no_ea6ad7c6_like" ON "sales_salesorder" ("order_no" varchar_pattern_ops)
CREATE INDEX "sales_salesorder_created_by_id_0700fb7b" ON "sales_salesorder" ("created_by_id")
CREATE INDEX "sales_salesorder_customer_id_e8577187" ON "sales_salesorder" ("customer_id")
ALTER TABLE "sales_salesorderitem" ADD CONSTRAINT "sales_salesorderitem_product_id_75dab6e4_fk_inventory" FOREIGN KEY ("product_id") REFERENCES "inventory_product" ("id") DEFERRABLE INITIALLY DEFERRED
ALTER TABLE "sales_salesorderitem" ADD CONSTRAINT "sales_salesorderitem_sales_order_id_d97897fd_fk_sales_sal" FOREIGN KEY ("sales_order_id") REFERENCES "sales_salesorder" ("id") DEFERRABLE INITIALLY DEFERRED
CREATE INDEX "sales_salesorderitem_product_id_75dab6e4" ON "sales_salesorderitem" ("product_id")
CREATE INDEX "sales_salesorderitem_sales_order_id_d97897fd" ON "sales_salesorderitem" ("sales_order_id")
